<?php

/**
 * @file
 * Install content to be used later in tests.
 */

/**
 * Implements hook_install().
 */
function cu_dc_tests_install() {

  // Install text block beans.
  $beans[0] = array(
    'title' => 'Text Block A',
    'content' => 'Text Block A Content AAA',
    'delta' => 'block-a-1'
  );

  $beans[1] = array(
    'title' => 'Text Block B',
    'content' => 'Text Block B Content BBB',
    'delta' => 'block-b-2'
  );
  foreach ($beans as $key => $value) {
    $bean = bean_create(array('type' => 'block'));
    $bean->label = $value['title'];
    $bean->title = $value['title'];
    $bean->delta = $value['delta'];
    $bean->field_block_text = array(
      LANGUAGE_NONE => array(array(
        'value' => $value['content'],
      )),
    );
    $bean->save();
  }

  // Load beans for references
  $b1 = bean_load_delta('block-a-1');
  $b2 = bean_load_delta('block-b-2');

  // Create A/B Block 1
  $bean = bean_create(array('type' => 'a_b_block'));
  $bean->label = 'a-b-test-block-1';
  $bean->title = 'a-b-test-block-1';
  _cu_dc_tests_collection_item($bean, $b1->bid, 0, 100);
  _cu_dc_tests_collection_item($bean, $b2->bid, 1, 0);
  $bean->save();

  // Create A/B Block 2
  $bean = bean_create(array('type' => 'a_b_block'));
  $bean->label = 'a-b-test-block-2';
  $bean->title = 'a-b-test-block-2';
  _cu_dc_tests_collection_item($bean, $b1->bid, 0, 0);
  _cu_dc_tests_collection_item($bean, $b2->bid, 1, 100);
  $bean->save();

  _cu_dc_tests_add_users();


}

function _cu_dc_tests_collection_item($bean, $bid, $order, $percentage) {
  $fc_item = entity_create('field_collection_item', array('field_name' => 'field_block_option'));
  $fc_item->setHostEntity('bean', $bean);
  $fc_item->field_block[LANGUAGE_NONE][$order]['target_id'] = $bid;
  $fc_item->field_percentage[LANGUAGE_NONE][$order]['value'] = $percentage;
  $fc_item->save();
  return TRUE;
}


/**
 * Creates users needed for test runs.
 */
function _cu_dc_tests_add_users() {

  // List needed users.
  $users = array(
    'campaign_manager',
  );

  // Create users.
  foreach ($users as $user_name) {
    // For some reason, I ran into the issue where the same user was created multiple times.
    // If user exists, skip creation.
    if (user_load_by_name($user_name)) {
      continue;
    }

    // Get role ID.
    $role = user_role_load_by_name($user_name);
    $new_user = array(
      'name' => $user_name,
      'pass' => $user_name,
      'mail' => 'noreply@nowhere.com',
      'status' => 1,
      'init' => 'noreply@nowhere.com',
      'roles' => array(
        DRUPAL_AUTHENTICATED_RID => 'authenticated user',
        $role->rid => $user_name,
      ),
    );

    // The first parameter is sent blank so a new user is created.
    user_save('', $new_user);
  }
}
