<?php

/**
 * @file
 * Install content to be used later in tests.
 */

/**
 * Implements hook_install().
 */
function cu_dc_tests_install() {

  _cu_dc_tests_add_users();
}


/**
 * Creates users needed for test runs.
 */
function _cu_dc_tests_add_users() {

  // List needed users.
  $users = array(
    'campaign_manager',
  );

  // Create users.
  foreach ($users as $user_name) {
    // For some reason, I ran into the issue where the same user was created multiple times.
    // If user exists, skip creation.
    if (user_load_by_name($user_name)) {
      continue;
    }

    // Get role ID.
    $role = user_role_load_by_name($user_name);
    $new_user = array(
      'name' => $user_name,
      'pass' => $user_name,
      'mail' => 'noreply@nowhere.com',
      'status' => 1,
      'init' => 'noreply@nowhere.com',
      'roles' => array(
        DRUPAL_AUTHENTICATED_RID => 'authenticated user',
        $role->rid => $user_name,
      ),
    );

    // The first parameter is sent blank so a new user is created.
    user_save('', $new_user);
  }
}
