<?php
/**
 * @file
 * cu_wowza module.
 */

/**
 * Implements hook_codec_info().
 */
function cu_wowza_codec_info() {
  $codecs = array();

  $codecs['wowza'] = array(
    'name' => t('Wowza.com'),
    'sample_url' => 'https://player.cloud.wowza.com/hosted/[video_id]/player.html',
    'callback' => 'cu_wowza_video_filter',
    'regexp' => '/player\.cloud\.wowza\.com\/hosted\/([a-z0-9]+)\/player.html/i',
  );

  return $codecs;
}

/**
 * Callback function for Wowza codec.
 */
function cu_wowza_video_filter($video) {
  $html = '<div id="wowza_player"></div>
  <script id="player_embed" src="//player.cloud.wowza.com/hosted/' . $video['codec']['matches'][1] . '/wowza.js" type="text/javascript"></script>';
  return $html;
}
