<?php

/**
 * @file
 * Contains Drupal-related hooks for the Slate bundle.
 */


/**
 * Define site permissions in code.
 *
 * Create a secure_permissions_data module directory and place this function
 * in secure_permissions_data.module.
 *
 * @param string $role
 *   The role for which the permissions are being requested.
 *
 * @return array
 *   An array defining all the permissions for the site.
 */
function express_slate_bundle_secure_permissions($role) {
  $permissions = array(
    'administrator' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'view et_slate_form_bean embeds',
      'publish embeds',
      'unpublish embeds'
    ),
    'anonymous user' => array(
      'view et_slate_form_bean embeds',
      'view any et_beans_bean bean',
    ),
    'authenticated user' => array(
      'view et_slate_form_bean embeds',
      'view any et_beans_bean bean',
    ),
    'campaign_manager' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'view et_slate_form_bean embeds',
      'view any et_beans_bean bean',
      'publish embeds',
      'unpublish embeds',
      'delete embeds',
      'access navbar',
      'view the administration theme',
      'access content overview',
      'administer nodes',
    ),
    'developer' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'view et_slate_form_bean embeds',
      'view any et_beans_bean bean',
      'publish embeds',
      'unpublish embeds',
      'delete embeds'
    ),
    'site_owner' => array(
      'administer embed templates',
      'delete embeds',
      'edit et_slate_form_bean embeds',
      'view et_slate_form_bean embeds',
      'view any et_beans_bean bean',
      'publish embeds',
      'unpublish embeds',
      'delete embeds',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}


