<?php

/**
 * @return {array} A new library for the Vue 3 Web Components
 */
function cu_web_components_bean_library() {
  $libraries['ucb-vue-lib'] = array(
    'title' => 'UCB Vue Component Library',
    'website' => 'https://github.com/CuBoulder/vue3-sandbox',
    'version' => '1.0',
    'js' => array(
      libraries_get_path('vue') . '/vue.global.prod.js' => array('scope' => 'header'),
      libraries_get_path('vue') . '/dist/bundle.js' => array('scope' => 'footer', 'defer' => TRUE)
    ),
    'css' => array(
      libraries_get_path('vue') . '/dist/ucbWebComponentLib.css' => array('scope' => 'header')
    )
  );
  return $libraries;
}

/**
 * Implements hook_page_alter()
 */
function cu_web_components_bean_page_alter(&$page) {
  drupal_add_library('cu_web_components_bean', 'ucb-vue-lib');
}

/**
 * Implements hook_secure_permissions()
 */
function cu_web_components_bean_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'view any cu_web_components_bean bean',
    ),
    'authenticated user' => array(
      'view any cu_web_components_bean bean',
    ),
    'administrator' => array(
      'create any cu_web_components_bean bean',
      'delete any cu_web_components_bean bean',
      'edit any cu_web_components_bean bean',
      'view any cu_web_components_bean bean',
    ),
    'edit_my_content' => array(
      'view any cu_web_components_bean bean',
    ),
    'edit_only' => array(
      'edit any cu_web_components_bean bean',
      'view any cu_web_components_bean bean',
    ),
    'developer' => array(
      'create any cu_web_components_bean bean',
      'delete any cu_web_components_bean bean',
      'edit any cu_web_components_bean bean',
      'view any cu_web_components_bean bean',
    ),
    'site_editor' => array(
      'create any cu_web_components_bean bean',
      'delete any cu_web_components_bean bean',
      'edit any cu_web_components_bean bean',
      'view any cu_web_components_bean bean',
    ),
    'site_owner' => array(
      'create any cu_web_components_bean bean',
      'delete any cu_web_components_bean bean',
      'edit any cu_web_components_bean bean',
      'view any cu_web_components_bean bean',
    ),
  );
  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}

/**
 * Implements hook_bean_types_api_info().
 */
function cu_web_components_bean_bean_types_api_info() {
  return array('api' => 4);
}

/**
 * Ajax callback for the Bean config form. Callback updates the options dropdown and sets the API endpoint URL
 *
 * @return {array} Return the form element that is  being updated
 */
function ajax_wc_data_options_callback($form, $form_state) {
  $data_options = $form['wc_name']['#args'];
  $selected_wc = $form_state['input']['wc_name'];
  $arr = []; $options = []; $url = '';
  foreach($data_options as $key => $i) {
    if($key == $selected_wc){
      $url = $i['api_endpoint'];
      if($i['options'] !== 'none') {
        $arr = explode(', ', $i['options']);
      }
      break;
    }
  }
  if(count($arr) === 0) {
   $form['data_options']['#description'] = 'There are no data options for this web component';
   $form['data_options']['wc_data_option']['#options'] = ['default' => '-- WC Data Options --'];
  }
  else{
    foreach($arr as $key => $i) {
      $options[$i] = $i;
    }
    $form['data_options']['#description'] = 'Please select what data you want to show from this data source.';
    $form['data_options']['wc_data_option']['#options'] = $options;
  }
  $form['data_options']['api_endpoint']['#value'] = $url;
  return $form['data_options'];
}

/**
 * Bean appears in UI but cannot be edited
 *
 * Implements hook_bean_types()
 */
function cu_web_components_bean_bean_types() {
  $plugins = array();
  $plugins['cu_web_components_bean'] = array(
    'label' => t('CU Web Component'),
    'description' => t('A list of web components created in Vue'),
    'handler' => array(
      'class' => 'CUWebComponent',
      'parent' => 'bean',
      'path' => drupal_get_path('module', 'cu_web_components_bean') . '/plugins/bean',
      'file' => 'CUWebComponent.class.php',
    )
  );
  return $plugins;
}

/**
 * Create a new theme
 * 
 * Implements hook_theme()
 */
function cu_web_components_bean_theme($existing, $type, $theme, $path) {
  $theme = array();
  $theme['bean__cu_web_components_bean'] = array(
    'base hook' => 'bean',
    'template' => 'bean--cu_web_components_bean',
    'path' => drupal_get_path('module', 'cu_web_components_bean'),
    'variables' => ['api_endpoint' => NULL, 'wc_name' => NULL, 'resource_id' => NULL, 'wc_data_option' => NULL, 'bean_title' => NULL]
  );
  return $theme;
}
