<?php

/**
 * Enable google_cse. Set search to custom cse if google_cse_cx is set.
 */
function cu_search_update_7003() {
  module_enable(array('google_cse'));
  if (variable_get('google_cse_cx', NULL)) {
    variable_set('cu_search_options', array('this' => 'this'));
  }
}

/**
 * Set attribute to have search links open in same window.
 */
function cu_search_update_7004() {
  variable_set('google_cse_tag_attributes', 'gname="google_cse" linkTarget="_top"');
}
