<?php

/**
 * @file
 * Code for the Faculty Publications feature.
 */

include_once 'cu_faculty_publications_bundle.features.inc';


/**
 * Implements hook_theme_registry_alter().
 *
 * Let Drupal know that we've got bean--faculty_publications.tpl.php in our module
 * directory.
 */
function cu_faculty_publications_bundle_theme_registry_alter(&$theme_registry) {
  $module_path = drupal_get_path('module', 'cu_faculty_publications_bundle');
  $theme_registry_copy = $theme_registry;
  _theme_process_registry($theme_registry_copy, 'phptemplate', 'theme_engine', 'bean', $module_path);
  $theme_registry += array_diff_key($theme_registry_copy, $theme_registry);
  $hooks = array('bean');
  foreach ($hooks as $h) {
    if (isset($theme_registry[$h]['theme paths'])) {
      $first_element = array_shift($theme_registry[$h]['theme paths']);
      array_unshift($theme_registry[$h]['theme paths'], array_shift($theme_registry[$h]['theme paths']), $module_path);
    }
  }
}

/**
  * Implements hook_theme().
  */
function cu_faculty_publications_bundle_theme(&$existing, $type, $theme, $path) {
  $registry = array();
  $template_dir = drupal_get_path('module', 'cu_faculty_publications_bundle') . '/templates';
  $registry['faculty_publication'] = array(
    'template' => 'faculty-publication',
    'path' => $template_dir,
  );
  return $registry;
}


function cu_faculty_publications_bundle_preprocess_entity(&$vars) {
  $entity_type = $vars['elements']['#entity_type'];
  $bundle = $vars['elements']['#bundle'];
  if ($vars['elements']['#bundle'] == 'faculty_publications') {

    // This is the endpoint for faculty publications and where we want to display.
    $endpoint = variable_get('cu_faculty_publications_endpoint', 'https://experts.colorado.edu/es/fispubs-v1/publication/_search');
    // This is the endpoint to get more information about a particular faculty member.
    $fisEndpoint = variable_get('cu_faculty_fis_endpoint', 'https://experts.colorado.edu/es/fis/_search');

    $arguments = array();

    // Check for publication date filter.
    if (!empty($vars['bean']->field_faculty_publication_date)) {
      $date1 = strtotime($vars['bean']->field_faculty_publication_date[LANGUAGE_NONE][0]['value']);
      $date2 = strtotime($vars['bean']->field_faculty_publication_date[LANGUAGE_NONE][0]['value2']);

      $date1 = date('Y-m-d', $date1);
      $date2 = date('Y-m-d', $date2);
      $arguments[] = 'publicationDate:[' . $date1 . '%20TO%20' . $date2 . ']';
    }
    // Update endpoint url with filter parameters.
    $endpoint = $endpoint . '?q=' . join('&', $arguments);

    // Check for author email.
    if (!empty($vars['bean']->field_faculty_publication_email)) {
      $email = $vars['bean']->field_faculty_publication_email[LANGUAGE_NONE][0]['email'];
        $fisEndpoint .= '?q=email:"' . $email . '"';
        $emailResponse = drupal_http_request($fisEndpoint);

      if ($emailResponse->code == '200') {
        $emailResult = drupal_json_decode($emailResponse->data, true);
        $orcid = $emailResult['hits']['hits'][0]['_source']['orcid'];

        if ($orcid) {
          $endpoint .= '%20AND%20authors.orcid:"' . $orcid . '"';
        }
        else {
          return $vars['content']['invalid_email']['#markup'] = "No results found for email $email.";
        }
      }
    }

    // Send query to facutly publications database.
    $items = array();
    $response = drupal_http_request($endpoint);
    if ($response->code == '200') {
      $result = drupal_json_decode($response->data, true);
      $total = $result['hits']['total'];
      $pages = ceil($total/10);
      $items = $result['hits']['hits'];
    }
    if (!empty($items)) {
      $publications = array();
      foreach ($items as $item) {
        $publication = $item['_source'];
        $publications[]['#markup'] = theme('faculty_publication', $publication);
      }
    }
    if (!empty($publications)) {
      $vars['content']['publications'] = $publications;
    }
    else {
      $vars['content']['no_results']['#markup'] = 'There are no results for your query.';
    }
  }
}


/**
 * Implements hook_secure_permissions().
 *
 * Adding permissions for newsletter
 */
function cu_faculty_publications_bundle_secure_permissions($role) {
  $permissions = array(
    'anonymous user' => array(
      'view any campus_news bean',
    ),
    'authenticated user' => array(
      'view any faculty_publications bean',
    ),
    'administrator' => array(
      'create any faculty_publications bean',
      'delete any faculty_publications bean',
      'edit any faculty_publications bean',
      'view any faculty_publications bean',
    ),
    'developer' => array(
      'create any faculty_publications bean',
      'delete any faculty_publications bean',
      'edit any faculty_publications bean',
      'view any faculty_publications bean',
    ),
    'edit_my_content' => array(
      'view any faculty_publications bean',
    ),
    'edit_only' => array(
      'edit any faculty_publications bean',
      'view any faculty_publications bean',
    ),
    'site_editor' => array(
      'create any faculty_publications bean',
      'delete any faculty_publications bean',
      'edit any faculty_publications bean',
      'view any faculty_publications bean',
    ),
    'site_owner' => array(
      'create any faculty_publications bean',
      'delete any faculty_publications bean',
      'edit any faculty_publications bean',
      'view any faculty_publications bean',
    ),
  );

  if (isset($permissions[$role])) {
    return $permissions[$role];
  }
}
