<?php

/**
 * @file
 * Install content to be used later in tests.
 */

/**
 * Implements hook_install().
 */
function cu_dc_tests_install() {
  // Install text block beans.
  $beans[0] = array(
    'title' => 'Text Block A',
    'content' => 'Text Block A Content AAA',
    'delta' => 'block-a-1'
  );

  $beans[1] = array(
    'title' => 'Text Block B',
    'content' => 'Text Block B Content BBB',
    'delta' => 'block-b-2'
  );

  foreach ($beans as $key => $value) {
    $bean = bean_create(array('type' => 'block'));
    $bean->label = $value['title'];
    $bean->title = $value['title'];
    $bean->delta = $value['delta'];
    $bean->field_block_text = array(
      LANGUAGE_NONE => array(
        array(
          'value' => $value['content'],
        )
      ),
    );
    $bean->save();
  }

  _cu_dc_tests_add_users();
}

/**
 * Implements hook_enable().
 *
 * Set block field autocomplete to be a select list.
 */
function cu_dc_tests_enable() {
  $instance_info = field_info_instance('field_collection_item', 'field_block_row_block', 'field_block_row_collection');

  $instance_info['widget']['type'] = 'options_select';
  $instance_info['widget']['module'] = 'options';

  field_update_instance($instance_info);
}

/**
 * Creates users needed for test runs.
 */
function _cu_dc_tests_add_users() {

  // List needed users.
  $users = array(
    'campaign_manager',
  );

  // Create users.
  foreach ($users as $user_name) {
    // For some reason, I ran into the issue where the same user was created multiple times.
    // If user exists, skip creation.
    if (user_load_by_name($user_name)) {
      continue;
    }

    // Get role ID.
    $role = user_role_load_by_name($user_name);
    $new_user = array(
      'name' => $user_name,
      'pass' => $user_name,
      'mail' => 'noreply@nowhere.com',
      'status' => 1,
      'init' => 'noreply@nowhere.com',
      'roles' => array(
        DRUPAL_AUTHENTICATED_RID => 'authenticated user',
        $role->rid => $user_name,
      ),
    );

    // The first parameter is sent blank so a new user is created.
    user_save('', $new_user);
  }
}
