<?php
/**
  * @file
  * Code for the CU Search Box block.
  */

/**
  * Implements hook_menu
  */
function cu_search_box_menu() {
  $items['admin/config/system/cu-search-box'] = array(
    'title' => 'CU Search Box Settings',
    'description' => 'Configure how to search your CU Web Express website.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('cu_search_box_settings_form'),
  );
  $items['cu-search-box/results'] = array(
    'title' => t("you made a search!"),
    'page callback' => 'cu_search_box_results_page',
    'access callback' => TRUE
  );
  return $items;
}

function cu_search_box_settings_form($form, &$form_state) {
  $form = array(
    '#type' => 'markup',
    '#markup' => '<h3>' . t('Someday you will be able to make some settings here.') . '</h3>'
  );
}

function cu_search_box_results_page() {
  $page = array(
    '#type' => 'markup',
    '#markup' => 'Yes you did.'
  );
  return $page;
}

/**
  * Implements hook_bolck_info()
  */
function cu_search_box_block_info() {
  $blocks = array();
  $blocks['cu_search_box'] = [
    'info' => t('CU Search Box'),
    'region' => 'content',
    'status' => TRUE,
    'visibility' => BLOCK_VISIBILITY_LISTED,
    'pages' => '<front>\r\nnode/1\r\ncu-search-box/results',
    'cache' => DRUPAL_NO_CACHE
  ];

  return $blocks;
}

/**
  * Implements hook_node_access()
  */
function cu_search_box_node_access($node, $op, $account) {
  if ($node === 'cu_search_box') {
    return NODE_ACCESS_ALLOW;
  }
}

/**
  * Implements hook_block_view()
  */
function cu_search_box_block_view($delta = '') {
  if ($delta === 'cu_search_box') {
    $searchBoxSettings = variable_get('cu_search_box_settings', NULL);
    $block = [];

    $search_form = drupal_get_form('cu_search_box_search_form');
    dpm($search_form);
    $block['content']['search_form'] = $search_form;

    $search_background_image = $searchBoxSettings['background_image'] ? $searchBoxSettings['background_image'] : '';
    $block['content']['#prefix'] = '<div id="cu-search-box" style="background-image:url(' . $search_background_image . ');">';    
    $block['content']['#suffix'] = '</div>';

    if ($searchBoxSettings['content']) {
      $search_content = check_markup($searchBoxSettings['content']['value'], $searchBoxSettings['content']['format']);
      $block['subject'] = '';
      $block['content']['search_content']['#markup'] = $search_content;
      $block['content']['search_content']['#prefix'] = '<div class="libraries-search-content">';
      $block['content']['search_content']['#suffix'] = '</div>';
    }
    return $block;
  }
}

function cu_search_box_search_form($form, &$form_state) {
  $searchBoxSettings = variable_get('cu_search_box_settings', NULL);
  $placeholderText = $searchBoxSettings['placeholder_text'] ? $searchBoxSettings['placeholder_text'] : 'Search';

  $form = array();
  $form['search_box'] = array(
    '#type' => 'fieldset',
    '#title' => $searchBoxSettings['title'] ? $searchBoxSettings['title'] : 'Search',
    '#title_display' => 'invisible',
    '#attributes' => array('class' => array('container-inline search-box')),
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );
  $form['search_box']['search_string'] = array(
    '#type' => 'textfield',
    '#attributes' => array('placeholder' => $placeholderText),
    '#title' => 'Query',
    '#title_display' => 'invisible',
  );
  $form['search_box']['search_type'] = array(
    '#type' => 'select',
    '#options' => cu_search_box_options(),
    '#title' => 'Search Type',
    '#title_display' => 'invisible',
  );
  $form['search_box']['search_submit'] = array(
    '#type' => 'submit',
    '#value' => 'Search',
    '#prefix' => '<div class="form-submit-wrapper">',
    '#suffix' => '</div>',
  );
  $form['#submit'][] = 'cu_search_box_form_submit';
  dpm($form);
  return $form;
}

function cu_search_box_form_submit($form, &$form_state) {
  if ($form_state['values']['search_string'] == 'Yo!') {
    $form_state['redirect'] = '/cu-search-box/results';
  }
}

function cu_search_box_options() {
  return ['option1' => 1, 'option2' => 2];
}