<?php

/**
 * @file
 * Contains Drupal hooks for the Tracking Pixels module.
 */

/**
 * Implements hook_embed_templates_types().
 *
 * @return array
 *   List of custom embed types.
 */
function cu_embed_chat_widget_cu_js_embed_types() {
  // Create a few initial embed types.
  $custom_types = array();
  $module_path = drupal_get_path('module', 'cu_embed_chat_widget');
  $default_status = 'unpublished';

  $custom_types['admithub'] = array(
    'label' => 'AdmitHub',
    'form_callback' => 'cu_embed_chat_widget_admithub_form',
    'submission_callback' => NULL,
    'renderer' => 'page_top_bottom',
    'default_status' => $default_status,
    'path' => $module_path,
    'template' => 'templates/admithub',
  );

  $custom_types['livechat'] = array(
    'label' => 'LiveChat',
    'form_callback' => 'cu_embed_chat_widget_livechat_form',
    'submission_callback' => NULL,
    'renderer' => 'page_top_bottom',
    'default_status' => $default_status,
    'path' => $module_path,
    'template' => 'templates/livechat',
  );

  return $custom_types;
}



/**
 * Form values for Facebook tracking pixel.
 *
 * @param array $form
 *   Form containing default embed template form options.
 * @param array $form_state
 *   State of the default embed template form.
 * @param int|null $id
 *   ID of the current embed being edited if that embed exists.
 * @param array $data
 *   Data of the current embed if it is being edited.
 */
function cu_embed_chat_widget_admithub_form(&$form, &$form_state, $id = NULL, $data = array()) {
  $form['options']['account_id'] = array(
    '#title' => t('License ID'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['account_id']) ? $data['account_id'] : '',
    '#required' => TRUE,
    '#size' => 128,
  );
}

/**
 * Form values for Facebook tracking pixel.
 *
 * @param array $form
 *   Form containing default embed template form options.
 * @param array $form_state
 *   State of the default embed template form.
 * @param int|null $id
 *   ID of the current embed being edited if that embed exists.
 * @param array $data
 *   Data of the current embed if it is being edited.
 */
function cu_embed_chat_widget_livechat_form(&$form, &$form_state, $id = NULL, $data = array()) {
  $form['options']['account_id'] = array(
    '#title' => t('License ID'),
    '#type' => 'textfield',
    '#default_value' => !empty($data['account_id']) ? $data['account_id'] : '',
    '#required' => TRUE,
    '#size' => 128,
  );
}
