name: Apply-Contrib-Patches

on:
  pull_request:    
    branches: 
      - dev_alans
jobs:
  apply-patches:
    name: Check for Changes - Apply Patches
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # - uses: ./.github/workflows/action-apply-contrib-patches
    - run: git diff --quiet $GITHUB_REF..dev_alans -- modules/contrib || git apply patches/*
    - run: git add .
    - run:  git commit -m "applying patches to contrib modules"
