name: Run Behat Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports: [3306]
        env:
          DATABASE: drupal
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_ENCODING: utf8

    steps:

    # - name: Make a comment
    #   uses: mshick/add-pr-comment@v1
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     message: |
    #       **Tue3**

    - name: Checkout d7Core Repository
      uses: actions/checkout@v2
      with:
        repository: CuBoulder/d7core
        path: drupal

    - name: Checkout Pull Request's Commit
      uses: actions/checkout@v2
      with:
        path: drupal/profiles/express

    - name: Install Dependencies With Composer
      run: |
        cd drupal
        ROOT_DIR=`pwd`
        composer require "drush/drush:8.*"
        cd "$ROOT_DIR/profiles/express/tests/behat"
        composer update
        composer install --prefer-dist --no-interaction
        ./bin/behat --version
        cd $ROOT_DIR
        ./vendor/bin/drush --version

    # - name: Install Composer
    #   uses: php-actions/composer@v5
    #   with:
    #     php_version: 7.2
