name: Run Behat Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    # - name: Make a comment
    #   uses: mshick/add-pr-comment@v1
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     message: |
    #       **Tue3**

    - name: Checkout d7Core Repository
      uses: actions/checkout@v2
      with:
        repository: CuBoulder/d7core
        path: drupal

    - name: Checkout Pull Request's Commit
      uses: actions/checkout@v2
      with:
        path: drupal/profiles/express

    - name: Set PHP Version
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.4
        tools: composer:v1
        extensions: mysqli, PDO, xml, openssl, mbstring, gd

    - name: Start Mysql DB
      run: |
        sudo /etc/init.d/mysql start

    - name: Print Mysql, php and composer versions
      run: |
        mysql --version
        php --version
        composer --version

    - name: Install Drush 8
      run: |
        pwd && ls
        cd drupal
        composer require "drush/drush:8.*"
        ./vendor/bin/drush --version

    - name: Install Behat
      run: |
        pwd && ls
        cd drupal/profiles/express/tests/behat
        composer install --prefer-dist --no-interaction
        ./bin/behat --version

    - name: Install Express and needed modules
      run: |
        pwd && ls
        # Memcache module causes some problems. Remove it.
        rm -rf drupal/profiles/express/modules/contrib/memcache
        # Start server.
        drupal/vendor/bin/drush si express --db-url=mysql://root:root@127.0.0.1:3306/drupal --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Express" --yes
        drupal/vendor/bin/drush runserver > /dev/null 2>&1 &
        drupal/vendor/bin/drush status

        # Install cu_behat_tests.
        echo "Installing cu_behat_tests..."
        drupal/vendor/bin/drush en cu_behat_tests cu_users -y
        drupal/vendor/bin/drush pm-list
        drupal/vendor/bin/drush php-eval "variable_set('ldap_authentication_conf', array('authenticationMode' => 1));"
        sed -i s/_USERNAME_/${{ secrets.SAUCE_USERNAME }}/g drupal/profiles/express/tests/behat/behat.travis.yml
        sed -i s/_ACCESS_KEY_/${{ secrets.SAUCE_ACCESS_KEY }}/g drupal/profiles/express/tests/behat/behat.travis.yml

    - name: Run Ghoute driver tests
      run: |
        pwd && ls
        drupal/profiles/express/tests/behat/bin/behat --config drupal/profiles/express/tests/behat/behat.travis.yml --tags "@TestContent" --stop-on-failure

    # - name: Run js tests
    #   run: |
        # drupal/profiles/express/tests/behat/bin/behat --config drupal/profiles/express/tests/behat/behat.travis.yml --tags "~@broken&&@javascript" --verbose
