name: Run Behat Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports: [3306]
        env:
          DATABASE: drupal
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_ENCODING: utf8

    steps:

    # - name: Make a comment
    #   uses: mshick/add-pr-comment@v1
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     message: |
    #       **Tue3**

    - name: Checkout d7Core Repository
      uses: actions/checkout@v2
      with:
        repository: CuBoulder/d7core
        path: drupal

    - name: Checkout Pull Request's Commit
      uses: actions/checkout@v2
      with:
        path: drupal/profiles/express

    - name: Do Everything
      run: |

        echo -----
        echo "Starting MariaDB server..."
        mysql --host 127.0.0.1 --port ${{ job.services.mariadb.ports[3306] }} -uroot -proot -e "SHOW DATABASES;"

        # sudo /etc/init.d/mysql start
        # mysql --version
        # mysql -e "USE sys; select * from user_summary;" -proot -uroot


    # - name: Install Composer
    #   uses: php-actions/composer@v5
    #   with:
    #     php_version: 7.2
