name: Run Behat Tests

on:
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports: [3306]
        env:
          DATABASE: drupal
          DB_USERNAME: root
          DB_PASSWORD: root
          DB_ENCODING: utf8

    steps:

    # - name: Make a comment
    #   uses: mshick/add-pr-comment@v1
    #   with:
    #     repo-token: ${{ secrets.GITHUB_TOKEN }}
    #     message: |
    #       **Tue3**

    - name: Checkout d7Core Repository
      uses: actions/checkout@v2
      with:
        repository: CuBoulder/d7core
        path: drupal

    - name: Checkout Pull Request's Commit
      uses: actions/checkout@v2
      with:
        path: drupal/profiles/express

    - name: Install Dependencies With Composer
      run: |
        cd drupal
        ROOT_DIR=`pwd`
        composer require "drush/drush:8.*"
        cd "$ROOT_DIR/profiles/express/tests/behat"
        composer update
        composer install --prefer-dist --no-interaction
        ./bin/behat --version
        cd $ROOT_DIR
        ./vendor/bin/drush --version

    - name: Setup PHP and Express
      run: |
        sudo /etc/init.d/mysql start
        echo "PWD:"
        pwd
        cd drupal
        mkdir -p sites/default/files/styles/preview/public/gallery/ && chmod -R 777 sites
        # phpenv config-rm xdebug.ini
        # mysql -e 'create database drupal;' --user=root --password=root
        # cp profiles/express/tests/travis-ci/settings.travis.php sites/default/settings.php
        # # phpenv config-add $ROOT_DIR/profiles/express/tests/travis-ci/config/express-php.ini
        # mysql -e "SET @@global.innodb_file_per_table=0;"
        # mysql -e "SET @@global.innodb_flush_log_at_trx_commit=2;"
        # php -i | grep memory
        # cat /proc/meminfo
        # cd profiles/express
        # echo Installing Express...
        # $ROOT_DI.vendor/bin/drush si express --db-url=mysql://root:@127.0.0.1 --account-name=admin --account-pass=admin --site-mail=admin@example.com --site-name="Express" --yes
        # echo Exporting database...
        # $ROOT_DI.vendor/bin/drush sql-dump --result-file=$HOME/cache/express.sql
        # $ROOT_DI.vendor/bin/drush pm-info travis_hosting
        # $ROOT_DI.vendor/bin/drush pm-info ng_hosting
        # $ROOT_DI.vendor/bin/drush pm-info cu_core
        # $ROOT_DI.vendor/bin/drush pm-info cu_ldap
        # $ROOT_DI.vendor/bin/drush pm-info cu_local_users
        # $ROOT_DI.vendor/bin/drush pm-list


    # - name: Install Composer
    #   uses: php-actions/composer@v5
    #   with:
    #     php_version: 7.2
